const faker = require('faker');

module.exports = {
    async player() {
        const data = await global.models.Player.create({
            steam: 'STEAM_1:1:' + faker.random.number(0, 33999999),
            name: faker.name.firstName(),
            lastip: faker.internet.ip(),
            score: faker.random.number(),
            kills: faker.random.number(),
            deaths: faker.random.number(),
            assists: faker.random.number(),
            suicides: faker.random.number(),
            tk: faker.random.number(),
            shots: faker.random.number(),
            hits: faker.random.number(),
            headshots: faker.random.number(),
            connected: faker.random.number(),
            rounds_tr: faker.random.number(),
            rounds_ct: faker.random.number(),
            lastconnect: faker.random.number(),
            knife: faker.random.number(),
            glock: faker.random.number(),
            hkp2000: faker.random.number(),
            usp_silencer: faker.random.number(),
            p250: faker.random.number(),
            deagle: faker.random.number(),
            elite: faker.random.number(),
            fiveseven: faker.random.number(),
            tec9: faker.random.number(),
            cz75a: faker.random.number(),
            revolver: faker.random.number(),
            nova: faker.random.number(),
            xm1014: faker.random.number(),
            mag7: faker.random.number(),
            sawedoff: faker.random.number(),
            bizon: faker.random.number(),
            mac10: faker.random.number(),
            mp9: faker.random.number(),
            mp7: faker.random.number(),
            ump45: faker.random.number(),
            p90: faker.random.number(),
            galilar: faker.random.number(),
            ak47: faker.random.number(),
            scar20: faker.random.number(),
            famas: faker.random.number(),
            m4a1: faker.random.number(),
            m4a1_silencer: faker.random.number(),
            aug: faker.random.number(),
            ssg08: faker.random.number(),
            sg556: faker.random.number(),
            awp: faker.random.number(),
            g3sg1: faker.random.number(),
            m249: faker.random.number(),
            negev: faker.random.number(),
            hegrenade: faker.random.number(),
            flashbang: faker.random.number(),
            smokegrenade: faker.random.number(),
            inferno: faker.random.number(),
            decoy: faker.random.number(),
            taser: faker.random.number(),
            mp5sd: faker.random.number(),
            breachcharge: faker.random.number(),
            head: faker.random.number(),
            chest: faker.random.number(),
            stomach: faker.random.number(),
            left_arm: faker.random.number(),
            right_arm: faker.random.number(),
            left_leg: faker.random.number(),
            right_leg: faker.random.number(),
            c4_planted: faker.random.number(),
            c4_exploded: faker.random.number(),
            c4_defused: faker.random.number(),
            ct_win: faker.random.number(),
            tr_win: faker.random.number(),
            hostages_rescued: faker.random.number(),
            vip_killed: faker.random.number(),
            vip_escaped: faker.random.number(),
            vip_played: faker.random.number(),
            mvp: faker.random.number(),
            damage: faker.random.number(),
            match_win: faker.random.number(),
            match_draw: faker.random.number(),
            match_lose: faker.random.number(),
            first_blood: faker.random.number(),
            no_scope: faker.random.number(),
            no_scope_dis: faker.random.number()
        });

        return data.dataValues;
    }
}